train_tag: 'example'
cuda_device: '0'

num_classes: 2
batch_size: 8
learning_rate: 1.e-4
total_epoch: 100
steps: [10, 30, 60]
seed: 0
train_path: ''
valid_path: ''
data_root: ''
class_weight: [[1, 10]]

num_workers: 8
weight_decay: 5.e-4
momentum: 0.9