train_tag: 'example'
cuda_device: '0'

num_classes: 2
batch_size: 4
learning_rate: 1.e-5
total_epoch: 100
steps: [10, 30, 60]
seed: 0

train_class_weight: [1., 3.3]
valid_class_weight: [1., 3.7]
train_path: ''
valid_path: ''

view_dropout: True
drop_rate: 0.2
add_bias: True
clip_size: 64

num_workers: 8
weight_decay: 5.e-4
momentum: 0.9